version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/data
      - ./ansible:/ansible
    environment:
      - DATABASE_URL=sqlite:///data/otg-tak.db
      - PYTHONUNBUFFERED=1
    networks:
      - otg-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - otg-network

networks:
  otg-network:
    driver: bridge
