---
# Security Hardening Playbook
- name: Harden Server Security
  hosts: all
  become: yes
  
  tasks:
    - name: Install security tools
      apt:
        name:
          - lynis
          - fail2ban
          - ufw
          - aide
          - rkhunter
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Configure UFW firewall
      ufw:
        state: enabled
        policy: deny
        direction: incoming
    
    - name: Allow SSH
      ufw:
        rule: allow
        port: '22'
        proto: tcp
    
    - name: Allow TAK Server port
      ufw:
        rule: allow
        port: '8089'
        proto: tcp
    
    - name: Allow HTTPS
      ufw:
        rule: allow
        port: '443'
        proto: tcp
    
    - name: Configure fail2ban
      copy:
        dest: /etc/fail2ban/jail.local
        content: |
          [DEFAULT]
          bantime = 3600
          findtime = 600
          maxretry = 5
          
          [sshd]
          enabled = true
        mode: '0644'
      notify: restart fail2ban
    
    - name: Run Lynis audit
      command: lynis audit system --quick
      register: lynis_output
      changed_when: false
    
    - name: Save Lynis output
      copy:
        content: "{{ lynis_output.stdout }}"
        dest: /var/log/lynis-audit.log
        mode: '0644'
    
    - name: Setup Lynis cron job
      cron:
        name: "Daily Lynis audit"
        hour: "2"
        minute: "0"
        job: "/usr/bin/lynis audit system --cronjob > /var/log/lynis-daily.log 2>&1"
    
    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: restart sshd
    
    - name: Configure automatic security updates
      apt:
        name: unattended-upgrades
        state: present
      when: ansible_os_family == "Debian"
  
  handlers:
    - name: restart fail2ban
      systemd:
        name: fail2ban
        state: restarted
    
    - name: restart sshd
      systemd:
        name: sshd
        state: restarted
