---
# Networking Setup Playbook
- name: Configure Networking (Tailscale & Zerotier)
  hosts: all
  become: yes
  vars:
    tailscale_auth_key: "{{ lookup('env', 'TAILSCALE_AUTH_KEY') }}"
    zerotier_network_id: "{{ lookup('env', 'ZEROTIER_NETWORK_ID') }}"
  
  tasks:
    - name: Install Tailscale
      block:
        - name: Add Tailscale GPG key
          apt_key:
            url: https://pkgs.tailscale.com/stable/ubuntu/focal.gpg
            state: present
        
        - name: Add Tailscale repository
          apt_repository:
            repo: "deb https://pkgs.tailscale.com/stable/ubuntu focal main"
            state: present
        
        - name: Install Tailscale
          apt:
            name: tailscale
            state: present
            update_cache: yes
        
        - name: Start Tailscale
          command: tailscale up --authkey={{ tailscale_auth_key }}
          when: tailscale_auth_key != ""
      when: ansible_os_family == "Debian"
    
    - name: Install Zerotier
      block:
        - name: Download Zerotier install script
          get_url:
            url: https://install.zerotier.com
            dest: /tmp/zerotier-install.sh
            mode: '0755'
        
        - name: Install Zerotier
          command: /tmp/zerotier-install.sh
          args:
            creates: /usr/sbin/zerotier-one
        
        - name: Join Zerotier network
          command: zerotier-cli join {{ zerotier_network_id }}
          when: zerotier_network_id != ""
      when: ansible_os_family == "Debian"
