name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Build Backend Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy requirements to backend directory
        run: |
          if [ ! -f requirements.txt ]; then
            echo "Error: requirements.txt not found in root directory"
            exit 1
          fi
          cp requirements.txt backend/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: cywf/otg-tak-backend:latest
          cache-from: type=registry,ref=cywf/otg-tak-backend:latest
          cache-to: type=inline

  build-frontend:
    name: Build Frontend Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy package files to frontend directory
        run: |
          if [ ! -f package.json ]; then
            echo "Error: package.json not found in root directory"
            exit 1
          fi
          cp package.json frontend/
          if [ -f package-lock.json ]; then
            cp package-lock.json frontend/
            echo "Copied package-lock.json"
          else
            echo "No package-lock.json found, skipping..."
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: cywf/otg-tak-frontend:latest
          cache-from: type=registry,ref=cywf/otg-tak-frontend:latest
          cache-to: type=inline
